config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/resources')

  # Resources
  resources :resources, only: :index
  resources :bookings, except: :edit

  get 'upcoming_bookings', to: 'upcoming#index'

  # Custom routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  # Error pages
  %w[404 422 500].each do |code|
    get code, to: 'application#error', code: code
  end
end

app/models/booking.rb
class Booking < NexudusBase
  attr_accessor :id, :resource_id, :resource_name, :resource, :coworker_id,
                :coworker_full_name, :from_time, :to_time, :online, :updated_by,
                :friendly_start_date, :friendly_dates, :friendly_date, :friendly_times,
                :friendly_from_time, :friendly_to_time, :duration_in_minutes,
                :repeat_series_unique_id, :repeat_booking, :repeats, :repeat_every,
                :repeat_until, :repeat_on_mondays, :repeat_on_tuesdays, :repeat_on_wednesdays,
                :repeat_on_thursdays, :repeat_on_fridays, :repeat_on_saturdays, :repeat_on_sundays
  REQUEST_URI = '/spaces/bookings'.freeze
  # TODO: implement pagination handling
  PAGE_SIZE = 'size=200'.freeze
  ORDERING = '&orderby=FromTime&dir=Descending'.freeze

  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::DateHelper

  def initialize(params)
    super
    if from_time.present? # protect against the times we're just quick-instantiating for a destroy
      load_friendly_dates
      load_friendly_times
      load_friendly_date
      load_duration_in_minutes
    end
  end

  class << self
    def find(id, options = {})
      booking = get("#{REQUEST_URI}/#{id}").parsed_response
      booking = new(booking)
      booking.public_send('resource=', booking.resource) if options[:include].present?
      booking
    end

    def all(coworker_id: nil, resource_ids: [], options: {})
      params = []
      params << "Booking_Coworker=#{coworker_id}" if coworker_id.present?
      # Expand booking time search boundaries a little bit if we have them
      if options[:from_time]
        options[:from_time] -= 1.day if options[:from_time] == options[:from_time].to_date.beginning_of_day
        params << "From_Booking_FromTime=#{options[:from_time].change(hour: 1, minutes: 0).utc.to_s(:nexudus)}"
      end
      params << "To_Booking_FromTime=#{options[:to_time].in(1.hour).utc.to_s(:nexudus)}" if options[:to_time]

      bookings = []
      if resource_ids.length == 1
        id = resource_ids.first
        result = get("#{REQUEST_URI}?#{(params + ["Booking_Resource=#{id}"]).join('&')}")['Records']
        bookings << result.map { |b| new(b) }
      else
        page_size = params.empty? ? PAGE_SIZE : "&#{PAGE_SIZE}"
        result = get("#{REQUEST_URI}?#{params.join('&')}#{page_size}#{ORDERING}")['Records']
        result = result.select { |b| resource_ids.include?(b['ResourceId']) } unless resource_ids.empty?
        bookings = result.map { |b| new(b) }
      end
      bookings.flatten.reject(&:blank?)
    end

    def upcoming_uncharged(coworker_id)
      params = []
      params << 'Booking_Invoiced=false'
      params << "Booking_Coworker=#{coworker_id}" if coworker_id.present?
      params << "From_Booking_FromTime=#{DateTime.now.utc.to_s(:nexudus)}"

      bookings = get("#{REQUEST_URI}?#{params.join('&')}")
      bookings = bookings ? bookings['Records'].map { |b| new(b) } : []
      bookings.flatten.reject(&:blank?).sort_by(&:from_time)
    end
  end

  def create
    attrs = Hash[instance_variables.map! { |name| [name.to_s.gsub(/@/, '').classify, instance_variable_get(name)] }]
    attrs = Hash[attrs.map { |k, v| [k.start_with?('RepeatOn') || k == 'Repeat' ? k.pluralize : k, v] }]
    self.class.post(REQUEST_URI, body: attrs.to_json, headers: { 'Content-Type' => 'application/json' })
  end

  def update
    attrs = Hash[instance_variables.map! { |name| [name.to_s.gsub(/@/, '').classify, instance_variable_get(name)] }]
    self.class.put(REQUEST_URI, body: attrs.to_json, headers: { 'Content-Type' => 'application/json' })
  end

  def destroy
    self.class.delete("#{REQUEST_URI}/#{id}")
  end

  def resource
    Resource.find(resource_id)
  end

  def formatted_from_time
    Time.zone.parse(from_time).to_s(:booking_time)
  end

  def formatted_to_time
    Time.zone.parse(to_time).to_s(:booking_time)
  end

  private

  def load_friendly_dates
    from = Time.zone.parse(from_time)
    to = Time.zone.parse(to_time)
    days = ((to - from) / 1.day).to_i

    if from >= Time.current && from < Time.current + 3.days
      self.friendly_dates = "In #{time_ago_in_words(from)} (#{from.to_s(:booking_short)})"
    else
      self.friendly_dates = from.to_s(:booking)
    end
    self.friendly_dates = "#{friendly_dates} (#{pluralize(days, 'day')})" if days > 1
  end

  def load_friendly_times
    self.friendly_from_time = formatted_from_time.strip
    self.friendly_to_time = formatted_to_time.strip
    self.friendly_times = "#{friendly_from_time} - #{friendly_to_time}"
  end

  def load_friendly_date
    self.friendly_date = Time.zone.parse(from_time).to_s(:booking_day)
  end

  def load_duration_in_minutes
    self.duration_in_minutes = (Time.zone.parse(to_time) - Time.zone.parse(from_time)) / 60
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :load_resources, only: [:index]

  def index
    @bookings = Booking.all(coworker_id: @coworker.id)
    @upcoming = @bookings.reject { |b| b.from_time.to_time < Time.now.utc }.sort_by(&:from_time)
    @past = @bookings.reject { |b| b.from_time.to_time > Time.now.utc }
  end

  def create
    date_times = process_date_times(params['bookingDate'], params['bookingFrom'], params['bookingTo'])
    unless current_user.can_book?(date_times[:fromTime], date_times[:toTime])
      flash[:alert] = "You don't have an ability to book tables on this date"
      return redirect_to resources_url
    end
    new_booking = {
      coworker_id: @coworker.id,
      resource_id: params['bookingResourceId'],
      from_time: date_times[:fromTime].to_s(:nexudus),
      to_time: date_times[:toTime].to_s(:nexudus),
      online: true
    }
    booking = Booking.new(new_booking)
    response = booking.create
    if (response = JSON.parse(response.body)) && response['WasSuccessful']
      session[:last_booking] = {
        id: response['Value']['Id'],
        from_time: date_times[:fromTime].to_s(:google_calendar),
        to_time: date_times[:toTime].to_s(:google_calendar),
        resource: Resource.find(new_booking[:resource_id]).try(:name)
      }
      redirect_to resources_url(anchor: 'recurring-container')
    else
      Rails.logger.info "BOOKING CREATE ERROR: #{response.inspect}"
      flash[:alert] = 'An error occurred while saving your booking. Please refresh the page and try again.'
      redirect_to resources_url
    end
  end

  def update
    if params[:booking_dates].present?
      dates = params[:booking_dates].split(';')
      old_booking = Booking.find(params[:id])
      result = true
      dates.each do |date_string|
        booking = update_recurring(old_booking, date_string)
        unless booking
          flash[:alert] = "You don't have an ability to book tables on this date"
          return redirect_to resources_url
        end
        response = booking.create
        result = result && (response = JSON.parse(response.body)) && response['WasSuccessful']
      end
      if result
        flash[:notice] = "Your #{'booking'.pluralize(dates.count)} #{'was'.pluralize(dates.count)} successfully saved!"
      else
        flash[:alert] = "Some of your bookings were not saved because one of the #{current_user.maker? ? 'tables' : 'stations'} has already been booked"
      end
    elsif params['bookingResource'].present?
      date_times = process_date_times(params['bookingDate'], params['bookingFrom'], params['bookingTo'])
      unless current_user.can_book?(date_times[:fromTime], date_times[:toTime]) &&
             Resource.can_book_resource?(date_times[:fromTime],
                                         date_times[:toTime],
                                         @coworker,
                                         params['bookingResource'])
        flash[:alert] = "You don't have an ability to book tables on this date"
        return redirect_to resources_url
      end
      booking_update = {
        id: params['bookingId'],
        coworker_id: @coworker.id,
        resource_id: params['bookingResource'],
        from_time: date_times[:fromTime].to_s(:nexudus),
        to_time: date_times[:toTime].to_s(:nexudus),
        online: true
      }
      booking = Booking.new(booking_update)
      response = booking.update
      if (response = JSON.parse(response.body)) && response['WasSuccessful']
        flash[:notice] = response['Message']
      else
        Rails.logger.info "BOOKING UPDATE ERROR: #{response.inspect}"
        flash[:alert] = 'An error occurred while updating your booking. Please refresh the page and try again.'
      end
    end

    redirect_to bookings_url
  end

  def destroy
    response = Booking.new('id' => params['id']).destroy
    if (response = JSON.parse(response.body)) && response['WasSuccessful']
      flash[:notice] = response['Message']
    else
      Rails.logger.info "BOOKING DESTROY ERROR: #{response.inspect}"
      flash[:alert] = 'An error occurred while canceling your booking. Please contact us.'
    end
    redirect_to bookings_url
  end

  private

  def load_resources
    @resources = Resource.all(role: current_user.role)
  end

  def update_recurring(old_booking, date_string)
    booking = old_booking.dup
    # Create a brand new one with the same settings but with recurring added
    booking.id = nil
    date = Time.strptime(date_string, Time::DATE_FORMATS[:booking_day])
    change_date = { month: date.month, day: date.day, year: date.year }
    # Change from & to dates for new booking
    plus_day = booking.from_time.to_datetime.in_time_zone.yday != booking.to_time.to_datetime.in_time_zone.yday
    from_time = booking.from_time.to_datetime.in_time_zone.change(change_date).utc
    to_time = (booking.to_time.to_datetime.in_time_zone.change(change_date) + (plus_day ? 1 : 0).day).utc
    return false unless Resource.can_book_resource?(from_time.to_datetime.in_time_zone,
                                                    to_time.to_datetime.in_time_zone,
                                                    @coworker,
                                                    booking.resource_id)
    booking.from_time = from_time
    booking.to_time = to_time
    booking
  end

  def process_date_times(day, from, to)
    from_time = convert_to_universal_time(day, from).utc
    to_time = convert_to_universal_time(day, to).utc
    from_time, to_time = adjust_for_next_day(from_time, to_time)
    {
      fromTime: from_time,
      toTime: to_time
    }
  end

  def adjust_for_next_day(from_time, to_time)
    # Add one day to toTime if the ending hour is "less" than the starting hour
    from_time += 1.day if from_time == from_time.to_date.beginning_of_day
    to_time += 1.day if to_time < from_time
    [from_time, to_time]
  end
end

app/views/bookings/_past_booking.html.haml
%tr
  %td{width: '35%'}
    .td-label Resource(s):
    = booking.resource.name
  %td{width: '35%'}
    .td-label Date(s):
    = booking.friendly_dates
  %td{width: '30%'}
    .td-label In/Out Time:
    = booking.friendly_times

app/views/bookings/_upcoming_booking.html.haml
%tr{id: booking.id}
  %td
    .td-label Resource(s):
    = booking.resource.name
  %td
    .td-label Date(s):
    = booking.friendly_dates
  %td
    .td-label In/Out Time:
    = booking.friendly_times
  %td
    = link_to '#', class: 'btn btn-default btn-sm btn-edit booking-edit', data: { id: booking.id } do
      %span.glyphicon.glyphicon-pencil{'aria-hidden': true}
      Edit
  - if ((Time.parse(booking.from_time) - Time.now) / 1.minute) <= booking.resource.late_cancellation_limit
    %td{data: {placement: 'left', toggle: 'tooltip'}, title: "Locked. This booking starts in less than #{booking.resource.late_cancellation_limit.to_i / 60} hours."}
      = link_to '#', class: 'btn btn-default btn-sm disabled' do
        %span.glyphicon.glyphicon-remove{'aria-hidden': true}
        Remove
  - else
    %td
      = link_to booking_path(id: booking.id), method: :delete, data: {confirm: "Are you sure you want to cancel this booking for #{booking.from_time.to_datetime.in_time_zone.strftime('%Y-%m-%d')}?"}, class: 'btn btn-default btn-sm' do
        %span.glyphicon.glyphicon-remove{'aria-hidden': true}
        Remove
%tr.hidden.edit-booking{id: "edit-booking-#{booking.id}", data: { booking: booking.to_json, resource: booking.resource.to_json }}
  %td{colspan: '5'}
    = form_for :booking, url: booking_path(id: booking.id), method: :put do |f|
      = f.hidden_field :id, value: booking.id, name: :id
      = f.hidden_field :id, value: booking.id, name: :bookingId
      = f.hidden_field :date, value: booking.friendly_date, name: :bookingDate
      %h3 Quick edit
      .col-sm-3
        .edit-label Resource(s):
        .edit-small Change your spot
        .form-group.form-inline
          = select_tag :bookingResource, options_from_collection_for_select(@resources, :id, :name, booking.resource_id), class: 'chosen-select form-control col-sm-5'
      .col-sm-3
        .edit-label Time of day:
        .edit-small Extend your hours
        = hidden_field_tag 'bookingFrom', booking.formatted_from_time, id: "bookingFrom-#{booking.id}"
        = hidden_field_tag 'bookingTo', booking.formatted_to_time, id: "bookingTo-#{booking.id}"
        .form-group.time-range
          .time-slider-range-holder{id: "time-slider-range-holder-#{booking.id}"}
            %span
          .time-slider-range{id: "filter-time-slider-#{booking.id}", data: {target: "#time-slider-range-holder-#{booking.id}", from_target: "#bookingFrom-#{booking.id}", to_target: "#bookingTo-#{booking.id}", from: booking.formatted_from_time, to: booking.formatted_to_time, edit: 'true'}}
          -#.dropdown.dropdown-time-range
          -#  = link_to 'javascript:void(0);', id: "time-slider-range-holder-#{booking.id}", 'data-toggle' => 'dropdown' do
          -#    = fa_icon 'pencil'
          -#    %span
          -#  %ul.dropdown-menu
          -#    %li
          -#      .time-slider-range{id: "filter-time-slider-#{booking.id}", data: {target: "#time-slider-range-holder-#{booking.id}", from_target: "#bookingFrom-#{booking.id}", to_target: "#bookingTo-#{booking.id}", from: booking.formatted_from_time, to: booking.formatted_to_time, edit: 'true'}}
      .col-sm-4.booking-info
        %label In Date:
        %span= booking.friendly_dates
        %br/
        %label Booked for:
        %span= booking.coworker_full_name
        %br/
        %label Booked by:
        %span= booking.updated_by
      .col-sm-2.text-right
        = f.submit 'Update', class: 'btn btn-primary', data: { disable_with: 'Saving...' }
        %a.booking-close{href: '#', data: { id: booking.id }} Close

app/views/bookings/index.html.haml
- if flash[:notice]
  .alert.alert-success.alert-dismissible{role: 'alert'}
    %button.close{'aria-label': 'Close', 'data-dismiss': 'alert', type: 'button'}
      %span{'aria-hidden': 'true'} ×
    %strong Success!
    = flash[:notice]
- if flash[:info]
  .alert.alert-info.alert-dismissible{role: 'alert'}
    %button.close{'aria-label': 'Close', 'data-dismiss': 'alert', type: 'button'}
      %span{'aria-hidden': 'true'} ×
    = flash[:info]
- if flash[:alert]
  .alert.alert-danger.alert-dismissible{role: 'alert'}
    %button.close{'aria-label': 'Close', 'data-dismiss': 'alert', type: 'button'}
      %span{'aria-hidden': 'true'} ×
    %strong Oh no!
    = flash[:alert]
.col-md-3
  %h1 Upcoming Kitchen Time
  %p
    Edit or cancel your bookings here but remember:
  %ol
    %li Bookings need to be at least 2 hours
    %li We need 24 hours notice to edit/cancel a booking
.col-md-9.reservations-tables
  %h2 Upcoming
  - if @upcoming.any?
    %table#upcoming-bookings.table.table-striped
      %thead
        %tr
          %th{width: '25%'} Resource(s)
          %th{width: '25%'} Date(s)
          %th{width: '25%'} In/Out Time
          %th{width: '25%', colspan: 2}
      %tbody
        = render partial: 'bookings/upcoming_booking', collection: @upcoming, as: :booking
  - else
    You don't have any upcoming bookings
  %br/
  - if @past.any?
    %h2 My Past Bookings
    #past-bookings
      %table.table.table-striped
        %thead
          %tr
            %th{width: '35%'} Resource(s)
            %th{width: '35%'} Date(s)
            %th{width: '30%'} In/Out Time
        %tbody
          = render partial: 'bookings/past_booking', collection: @past, as: :booking