config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/resources')

  # Resources
  resources :resources, only: :index
  resources :bookings, except: :edit

  get 'upcoming_bookings', to: 'upcoming#index'

  # Custom routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  # Error pages
  %w[404 422 500].each do |code|
    get code, to: 'application#error', code: code
  end
end

app/views/layouts/_nav_main.html.haml
/ main nav
%ul#nav-main.nav.navbar-nav.navbar-left
  %li.bookings-nav
    = link_to 'My Reservations', bookings_path
  %li.resources-nav
    = link_to 'Book Kitchen Time', resources_path
  %li.upcoming-nav
    = link_to 'Upcoming bookings', upcoming_bookings_path
  %li.info-nav
    %a{'data-toggle': 'popover', role: 'button', tabindex: '0', title: 'Important Information'}
      Important Information
  %li.accounts-nav
    %a{'data-toggle': 'popover', role: 'button', tabindex: '0', title: 'My Account'}
      =fa_icon 'user'
      My account
  #my_account_popover.hidden
    .row
      .col-sm-6
        %small You have
        %strong.text_blue.display-block#my-account-remaining-hours= pluralize(@coworker.remaining_hours_in_plan.to_i, 'hour')
        %small remaining this month
      .col-sm-6
        %small Your Plan:
        %strong.text_blue.display-block= @coworker.billing_plan
        %small
          (#{@coworker.total_hours_in_plan.to_i} hrs, #{number_to_currency(@coworker.extra_service_cost_per_hour)}/hr add'l)
    .row
      .col-sm-12
        = link_to 'Logout', logout_path, class: 'btn btn-primary user-logout'
  #information_popover.hidden
    .row.important-info-row
      .col-sm-4
        %small Emergencies: Callie's #
      .col-sm-8.pt-10
        %strong.text_blue.display-block
          %a{'href': 'tel:206-356-3739'} (206) 356-3739
    %hr.important-info-hr
    .row.important-info-row
      .col-sm-4
        %small Matt's #
      .col-sm-8
        %strong.text_blue.display-block
          %a{'href': 'tel:415-279-7337'} (415) 279-7337
    .row
      .col-sm-4
        %small Iso's #
      .col-sm-8
        %strong.text_blue.display-block
          %a{'href': 'tel:617-894-0597'} (617) 894-0597
    .row
      .col-sm-4
        %small Matt's Email
      .col-sm-8
        %strong.text_blue.display-block
          %a{'href': 'mailto:matt@foragekitchen.com'} matt@foragekitchen.com
    .row
      .col-sm-4
        %small Iso's Email
      .col-sm-8
        %strong.text_blue.display-block
          %a{'href': 'mailto:iso@foragekitchen.com'} iso@foragekitchen.com
    .row
      .col-sm-4
        %small Alarm Code
      .col-sm-8
        %strong.text_blue.display-block 1207
    .row
      .col-sm-4
        %small Gate Code
      .col-sm-8
        %strong.text_blue.display-block 4762

app/views/layouts/_nav_secondary.html.haml
/ secondary nav (will collapse on smaller screens)
#subnav-collapse-1.collapse.navbar-collapse.navbar-right
  %ul.nav.navbar-nav
    %li.dropdown
      = link_to 'Kitchen', 'http://www.foragekitchen.com/facilities', class: 'dropdown-toggle', role: 'button', 'aria-haspopup': 'true', 'aria-expanded': 'false', data: {toggle: 'dropdown'}
      %ul.dropdown-menu
        %li
          = link_to 'Facilities', 'http://www.foragekitchen.com/facilities'
        %li
          = link_to 'Membership Levels', 'http://www.foragekitchen.com/membershiplevels'
        %li
          = link_to 'Sign Up', 'http://www.foragekitchen.com/signup'
    %li
      = link_to 'Cafe', 'http://www.foragekitchen.com/cafe'
    %li
      = link_to 'About', 'http://www.foragekitchen.com/about'
    %li.sessions-nav
      = link_to 'Log In', login_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Forage Kitchen
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{name: :viewport, content: "width=device-width, initial-scale=1.0"}

    = tag('link', rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png')
    = tag('link', rel: 'icon', type: 'image/png', sizes: '32x32', href: '/favicon-32x32.png')
    = tag('link', rel: 'icon', type: 'image/png', sizes: '16x16', href: '/favicon-16x16.png')
    = tag('link', rel: 'manifest', href: '/manifest.json')
    = tag('link', rel: 'mask-icon', color: '#5bbad5', href: '/safari-pinned-tab.svg')
    = tag('meta', name: 'theme-color', content: '#ffffff')

    - unless Rails.env.test?
      = javascript_include_tag 'https://use.typekit.net/zxi1ibh.js'
      :javascript
        try{Typekit.load({ async: true });}catch(e){}
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    - if defined?(Timecop) && Timecop.top_stack_item
      - unix_millis = (Time.now.to_f * 1000.0).to_i
      = javascript_include_tag '/assets/sinon.js'
      :javascript
        sinon.useFakeTimers(#{unix_millis});
    = csrf_meta_tags
  %body{id: controller_name}
    %nav#nav-main.navbar.navbar-default
      .container-fluid
        .navbar-header
          / toggle nav button on responsive layout
          -if !user_signed_in?
            %button.navbar-toggle.collapsed{'aria-expanded': 'false', 'data-target': '#subnav-collapse-1', 'data-toggle': 'collapse', type: 'button'}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
          / logo
          = link_to image_tag('fk-logo.png', alt: 'Forage Kitchen'), 'http://www.foragekitchen.com/', class: 'navbar-brand'
          = render 'layouts/nav_main' if user_signed_in?
        = render 'layouts/nav_secondary' unless user_signed_in?
    .container-fluid
      = yield
    %footer
      .container-fluid
        = image_tag 'fk-fire.png', width: 130
        = link_to 'Work for the kitchen', '#', class: 'work-for-kitchen-link'
        .contact-info
          %span 478 25TH ST, OAKLAND, CA
          %span|
          = mail_to 'HELLO@FORAGEKITCHEN.COM'
        %ul.social-links
          %li= link_to fa_icon('twitter'), 'https://twitter.com/forageSF', target: '_blank'
          %li= link_to fa_icon('instagram'), 'https://www.instagram.com/foragesf/', target: '_blank'
          %li= link_to fa_icon('facebook'), 'https://www.facebook.com/isorabins', target: '_blank'